name: Blob service Deploy Fly io
on:
  push:
    branches: [master]
    paths:
      - blob-service/**
      - .github/workflows/deploy-blob-service.yml
jobs:
  deploy:
    defaults:
      run:
        working-directory: ./blob-service
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
